theme: jekyll-theme-minimal

title: Micro Meta App
description: Microscopy Metadata <span class="wraptastefully">for the real world!</span>

#logo: /images/Micro-Meta App_icon.png
logo: /images/Micro-Meta App_icon.png

show_downloads: true

github:
  win_url: https://github.com/qupath/qupath/releases/download/v0.2.1/QuPath-0.2.1-Windows.msi
  mac_url: https://github.com/qupath/qupath/releases/download/v0.2.1/QuPath-0.2.1-Mac.pkg
  linux_url: https://github.com/qupath/qupath/releases/download/v0.2.1/QuPath-0.2.1-Linux.tar.xz

  source_url: https://github.com/qupath/qupath
  docs_url: http://qupath.readthedocs.io
  discuss_url: https://forum.image.sc/tags/qupath

